
# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/ruby:2.6.1-node-browsers
#       - image: circleci/postgres

#     working_directory: ~/repo

#     steps:
#       -  run:
#           name: install_dependent_on_systems
#           command: apk add --update --no-cache linux-headers git openssh-client tar gzip build-base tzdata mariadb-dev
#       - checkout

#       # Download cache
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "Gemfile.lock" }}
#             - v1-dependencies-

#       - run:
#           name: install dependencies
#           command: |
#             bundle install --jobs=4 --retry=3 --path vendor/bundle
#       - save_cache:
#           paths:
#             - ./vendor/bundle
#           key: v1-dependencies-{{ checksum "Gemfile.lock" }}

#      #test
#       - run:
#           name: run tests
#           command: |
#             mkdir /tmp/test-results
#             TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
#               circleci tests split --split-by=timings)"
#             bundle exec rspec -- ${TEST_FILES}
#       # collect test date
#       - store_test_results:
#           path: /tmp/circleci-test-results

      - add_ssh_keys:
          fingerprints:
          - "${SSSH_KEY}"
           

#       - deploy:
#           name: deploy_with_Capistrano
#           command:
#               bundle exec cap production deploy
