version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
      - image: circleci/postgres

    working_directory: ~/repo

    steps:
      - checkout

      # Download cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

     #test
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"
            bundle exec rspec -- ${TEST_FILES}
      # collect test date
      - store_test_results:
          path: /tmp/circleci-test-results

      - add_ssh_keys:
          fingerprints:
             - "-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAvJvxRIP+lI0bD2EaT3CHsgznSXGMRJZzOJ6VnWd7fTKMr/rt
kngyJKmSEhy4pdKiN15E8zJn/V1RpRzlm2A82vbqcMu1KhBomznefzvCtWeguVrn
V1HN/Uj0fJ+fkP1zFB319lDzGiVdo+dCQ+0k1WkvMOCYKK7yRxDN3v/OLO6XlMWn
PSz+L1aMOwR5X1ODNIhQx/GYvHonUK2HN+NBLYij7ZADKLRWuF0vOtbJQ/zoLtO+
QeCto5qK53fkLlcQv7RTh7qOGFSXCQ64FpQcWdzSr44ROAEzTWEuCl1CLWM3ydLr
iZp3UOBDf8N7X7skmiwjYQnuW/omgINhFQXNPQIDAQABAoIBAGL06qxJGLw2IJl8
GALQBtIbRQpaof6mdUOiqNsSHU99wyTd4eH0YFKuCW6pVRPjpKqqMkDrFHZxjNG1
jJ5t6t/zpuORbbbpLwkqXpug7jKhcUlu8Wv2Br66lVQBqAW5hLRsV81pgXMZYb0K
K9FZzfaOnmzlmc/WolU48trqmfEmQs9gm2o/RbcTUQiVhgxCOMJ28Wl1j1GdnVIi
nqUPQ0NlCRudDn3FglqzsXnUPwHWMhfHKWHMtJlOi+BN/ReEiVaqI8AjWmFqv5bD
qsXEEMhHuR/2PPV2eqbyXfhTwIXQE2DR2bUrIKGgEsnC+HoCiWHAJp/gwr5iTE0B
Gk4pRN0CgYEA5ynZeCGk1fEpV0CoJrP0Ftsgk31yDObkQ+tvwTp656nfMAMp0uho
DN5UYUp/L2rYTP/1hdSLSsizbJTW+BmMBrpurOzyYKO377/YsY2sU9tOh7gpynP9
WNixxIfLyBP+5t06Be+T6nOqGtKk11nidZXQ+Nilr9mS0uMSmMsDBOcCgYEA0N+i
7PsvaWwVN87PX/m3MYcc6sFaJMcgqmARQNgOY1ZCao1i3+ekRDEcrJLL5vbJs7Mz
8xshp5LGBgm2VNSB5FybaGvHvAQhWuFm6d4u0BfegN8NCu58csWmjZdfOT2bnAf+
WPDtFP/uJ3irs42wku6TQTmqBcTnKzzpZ9utdDsCgYEA5krQ9lc+Kk1pTB2D55rb
j3GakJUm7CeSPP/ug+hIzUZ0rRZZsl4KWteb5JkdABZHit5ssXk/k69C4OefCegZ
khJldC1SgmhYNKdBsBFeHuSa5abZK3JGcR7gatSGdbtF9KVsysEU8Tttue8kfc50
R4SLfX4IApqVJTdHLaUCSv0CgYEAhF0kR19KhVkr/Qi+28hIskc4KQBMmr/h0HY+
mMQSIhtYzWM5xEBsFZa14BrKwlukKI+onSeVZTca7FqdRBbDFa8mAL9EfL51UL1E
VXIqYk6t/ybaghHtpWHhkRrbClAjW3apVT2gUE17Y2ISFR/2RLaRdKURPMSx5fGc
y+cnfV8CgYEA39+APqnxqFwrl48++tiP/ZS+RSl77tWmT2tSxTZzl/71EZtGkffY
54E/EEfzAaTUk/yFXx1QZe6DQHbNuNdDxHgAkUC+k6LvZmnuLHo5RG3RU+fuHaMv
drEf01HCHT8qZsG3vW1Ar20CVXuUyiSlp9T06S2ZhJNGS3AqwVrIbGM=
-----END RSA PRIVATE KEY-----"

  deploy:
      name: deploy_with_Capistrano
      command:
        bundel exec cap production deploy
