version: 2.1
executors:
  default:
    docker:
      - image: circleci/ruby:2.-node-browsers
      - image: circleci/mysql:5.6
      
      
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      - MYSQL_ROOT_HOST: '%'
      - RAILS_ENV: 'test'
      - BUNDLER_VERSION: 2.0.2

    working_directory: ~/repo 
    
commands:
  setup_bundler_and_cache:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.0.2
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
jobs:
  build:
    executor: default
    steps:
      - setup_bundler_and_cache
      
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      
      - add_ssh_keys:
          fingerprints:
            - "{$ SSH_KEY}"
            
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  RuboCop:
    executor: default
    steps: 
      - setup_bundler_and_cache
      - run:
          command: bundle exec rubocop --fail-level w --display-only-fail-level-offenses
          
  Rspec test:
    executor: default
    steps: 
      - setup_bundler_and_cache   
      - run:
          command: bundle exec rspec
   
  deploy:
    executor: default
    steps:
      - setup_bundler_and_cache
      #deploy with capistrano
      - run:
          name: Capistrano deploy
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              exit 0
            fi
            bundle exec cap production deploy
            
  say_complete:
    executor: default
    steps:
      - run:
        command: echo "deploy completed"
            
   
        
workflows:
  version: 2.1
  build_test_and_deploy:
    jobs:
      - build
      - RuboCop:
          requires:
            - build
      - Rspec test:
          requires:
            - build
      - deploy:
          requires:
            - RuboCop
            - Rspec test
      - say_complete:
          requires:
            - deploy
        
 
